/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
*
* @export
* @interface UserAccess
*/
export interface UserAccess {
    /**
    *
    * @type {string}
    */
    'app'?: UserAccessAppConst;
    /**
    *
    * @type {boolean}
    */
    'admin'?: boolean;
    /**
    *
    * @type {string}
    */
    'permission_set_id'?: string;
}
export declare const UserAccessAppConst: {
    readonly sales: "sales";
    readonly projects: "projects";
    readonly campaigns: "campaigns";
    readonly global: "global";
    readonly account_settings: "account_settings";
};
export type UserAccessAppConst = typeof UserAccessAppConst[keyof typeof UserAccessAppConst];
